package forestryonto;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.forestryspaces.org/onto#Borough
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BOROUGH.<p>
     * 
     */
    public static final OWLClass CLASS_BOROUGH = factory.getOWLClass(IRI.create("http://www.forestryspaces.org/onto#Borough"));

    /* ***************************************************
     * Class http://www.forestryspaces.org/onto#Jurisdiction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class JURISDICTION.<p>
     * 
     */
    public static final OWLClass CLASS_JURISDICTION = factory.getOWLClass(IRI.create("http://www.forestryspaces.org/onto#Jurisdiction"));

    /* ***************************************************
     * Class http://www.forestryspaces.org/onto#PSSite
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PSSITE.<p>
     * 
     */
    public static final OWLClass CLASS_PSSITE = factory.getOWLClass(IRI.create("http://www.forestryspaces.org/onto#PSSite"));

    /* ***************************************************
     * Class http://www.forestryspaces.org/onto#PSStatus
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PSSTATUS.<p>
     * 
     */
    public static final OWLClass CLASS_PSSTATUS = factory.getOWLClass(IRI.create("http://www.forestryspaces.org/onto#PSStatus"));

    /* ***************************************************
     * Class http://www.forestryspaces.org/onto#Park
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARK.<p>
     * 
     */
    public static final OWLClass CLASS_PARK = factory.getOWLClass(IRI.create("http://www.forestryspaces.org/onto#Park"));

    /* ***************************************************
     * Class http://www.forestryspaces.org/onto#ParkZone
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARKZONE.<p>
     * 
     */
    public static final OWLClass CLASS_PARKZONE = factory.getOWLClass(IRI.create("http://www.forestryspaces.org/onto#ParkZone"));

    /* ***************************************************
     * Class http://www.forestryspaces.org/onto#PlantingSpace
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLANTINGSPACE.<p>
     * 
     */
    public static final OWLClass CLASS_PLANTINGSPACE = factory.getOWLClass(IRI.create("http://www.forestryspaces.org/onto#PlantingSpace"));

    /* ***************************************************
     * Class http://www.forestryspaces.org/onto#Sanctuary
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SANCTUARY.<p>
     * 
     */
    public static final OWLClass CLASS_SANCTUARY = factory.getOWLClass(IRI.create("http://www.forestryspaces.org/onto#Sanctuary"));

    /* ***************************************************
     * Class http://www.forestryspaces.org/onto#Street
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STREET.<p>
     * 
     */
    public static final OWLClass CLASS_STREET = factory.getOWLClass(IRI.create("http://www.forestryspaces.org/onto#Street"));

    /* ***************************************************
     * Object Property http://www.forestryspaces.org/onto#hasBorough
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBOROUGH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBOROUGH = factory.getOWLObjectProperty(IRI.create("http://www.forestryspaces.org/onto#hasBorough"));

    /* ***************************************************
     * Object Property http://www.forestryspaces.org/onto#hasJurisdiction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASJURISDICTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASJURISDICTION = factory.getOWLObjectProperty(IRI.create("http://www.forestryspaces.org/onto#hasJurisdiction"));

    /* ***************************************************
     * Object Property http://www.forestryspaces.org/onto#hasPark
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPARK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPARK = factory.getOWLObjectProperty(IRI.create("http://www.forestryspaces.org/onto#hasPark"));

    /* ***************************************************
     * Object Property http://www.forestryspaces.org/onto#hasSanctuary
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSANCTUARY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSANCTUARY = factory.getOWLObjectProperty(IRI.create("http://www.forestryspaces.org/onto#hasSanctuary"));

    /* ***************************************************
     * Object Property http://www.forestryspaces.org/onto#hasSite
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSITE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSITE = factory.getOWLObjectProperty(IRI.create("http://www.forestryspaces.org/onto#hasSite"));

    /* ***************************************************
     * Object Property http://www.forestryspaces.org/onto#hasStatus
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSTATUS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSTATUS = factory.getOWLObjectProperty(IRI.create("http://www.forestryspaces.org/onto#hasStatus"));

    /* ***************************************************
     * Object Property http://www.forestryspaces.org/onto#hasStreet
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSTREET.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSTREET = factory.getOWLObjectProperty(IRI.create("http://www.forestryspaces.org/onto#hasStreet"));

    /* ***************************************************
     * Object Property http://www.forestryspaces.org/onto#hasZone
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASZONE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASZONE = factory.getOWLObjectProperty(IRI.create("http://www.forestryspaces.org/onto#hasZone"));

    /* ***************************************************
     * Data Property http://www.forestryspaces.org/onto#hasAcres
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASACRES.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASACRES = factory.getOWLDataProperty(IRI.create("http://www.forestryspaces.org/onto#hasAcres"));

    /* ***************************************************
     * Data Property http://www.forestryspaces.org/onto#hasCommunityBoard
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCOMMUNITYBOARD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCOMMUNITYBOARD = factory.getOWLDataProperty(IRI.create("http://www.forestryspaces.org/onto#hasCommunityBoard"));

    /* ***************************************************
     * Data Property http://www.forestryspaces.org/onto#hasCreatedDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCREATEDDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCREATEDDATE = factory.getOWLDataProperty(IRI.create("http://www.forestryspaces.org/onto#hasCreatedDate"));

    /* ***************************************************
     * Data Property http://www.forestryspaces.org/onto#hasDirection
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDIRECTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDIRECTION = factory.getOWLDataProperty(IRI.create("http://www.forestryspaces.org/onto#hasDirection"));

    /* ***************************************************
     * Data Property http://www.forestryspaces.org/onto#hasGeometry
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASGEOMETRY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASGEOMETRY = factory.getOWLDataProperty(IRI.create("http://www.forestryspaces.org/onto#hasGeometry"));

    /* ***************************************************
     * Data Property http://www.forestryspaces.org/onto#hasLocation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLOCATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLOCATION = factory.getOWLDataProperty(IRI.create("http://www.forestryspaces.org/onto#hasLocation"));

    /* ***************************************************
     * Data Property http://www.forestryspaces.org/onto#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("http://www.forestryspaces.org/onto#hasName"));

    /* ***************************************************
     * Data Property http://www.forestryspaces.org/onto#hasObjectID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASOBJECTID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASOBJECTID = factory.getOWLDataProperty(IRI.create("http://www.forestryspaces.org/onto#hasObjectID"));

    /* ***************************************************
     * Data Property http://www.forestryspaces.org/onto#hasUpdatedDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASUPDATEDDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASUPDATEDDATE = factory.getOWLDataProperty(IRI.create("http://www.forestryspaces.org/onto#hasUpdatedDate"));


}
